version: '3'
services:

  worker-alpine:
    depends_on:
      - redis
      - mongo
    build:
      context: ./worker-alpine
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./worker-alpine/mrq-config.py:/app/mrq-config.py

  worker-debian:
    depends_on:
      - redis
      - mongo
    build:
      context: ./worker-debian
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./worker-debian/mrq-config.py:/app/mrq-config.py

  manager:
    depends_on:
      - redis
      - mongo
    build:
      context: ./manager
      dockerfile: Dockerfile
    environment:
      MRQ_REDIS: "redis://redis:6379"
      MRQ_MONGODB_JOBS: "mongodb://mongo:27017/mrq"
    volumes:
      - ./manager/add_task.py:/app/add_task.py

  dashboard:
    depends_on:
      - redis
      - mongo
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      MRQ_REDIS: "redis://redis:6379"
      MRQ_MONGODB_JOBS: "mongodb://mongo:27017/mrq"
    command: mrq-dashboard

  mongo:
    image: mongo

  redis:
    image: redis:alpine
